# platform = multi_platform_all
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      append: true
      - contents:
          source: data:,ProcessSizeMax%3D0%0A
        filesystem: root
        mode: 0644
        path: /etc/systemd/coredump.conf
